---
title       : Interactive Documents with R
subtitle    : Slidify + Shiny
author      : Adam Preston
job         : R Hacker
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light      # 
widgets     : [bootstrap, quiz, shiny, interactive]          
mode        : selfcontained # {standalone, draft}
ext_widgets : {rCharts: [libraries/nvd3, libraries/highcharts]}



--- &radio

## Interactive Quiz

What is 1 + 1?

1. 1
2. _2_
3. 3
4. 4

*** .hint

This is a hint

*** .explanation

This is an explanation

--- 

## Interactive Chart

```{r echo = F, results = 'asis'}
require(rCharts)
haireye <- as.data.frame(HairEyeColor)
n1 <- nPlot(Freq ~ Hair, group = 'Eye', type = 'multiBarChart',
    data = subset(haireye, Sex == "Male")
)
n1$print('chart1')
```


---

## A Line Chart

```{r echo = F, opts.label = 'interactive', results = 'asis'}
require(rCharts)
a <- Highcharts$new()
a$chart(type = "spline")
a$series(data = c(1, 3, 2, 4, 5, 4, 6, 2, 3, 5, NA), dashStyle = "longdash")
a$series(data = c(NA, 4, 1, 3, 4, 2, 9, 1, 2, 3, 4), dashStyle = "shortdot")
a$legend(symbolWidth = 80)
a$print('chart3')
```

---

## Results = Markup

```{r echo = F, opts.label = 'interactive',  results = 'asis'}
require(xtable)
options(xtable.type = 'html')
xtable(head(mtcars))
```



--- &twocol

## You know you love ggplot, admit it

*** =left
```{r echo = F }
require(ggplot2)
qplot(wt, mpg, data = mtcars)
```

*** =right

Remember don't have more than 20 words on a slide.




















